server:
  port: 9999
spring:
  application:
    name: ship-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ship?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #配置路径匹配策略
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
cos:
  baseUrl: ############################
  accessKey: ###########################
  secretKey: ##########################
  regionName: ap-shanghai
  bucketName: meng-1314015467
  folderPrefix: /files
  avatarFolder: /avatar
